### ISSUE TITLE
Using AzureServiceBusTransport as the transport name causes conflicts with NServiceBus.Azure.Transports.WindowsAzureServiceBus

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.Transport.AzureServiceBus#10]
While adding support for this transport to ServiceControl, we ran into an issue. The acceptance tests of that project require a reference to all the supported transports, which includes both the existing ASB transport and now this one. However, the `AzureServiceBusTransport` class is in the same namespace in both projects so you can't actually use it when referencing both assemblies in the same project.

@SeanFeldman gave us some history on this decision but he and @danielmarbach and I felt it would be worth revisiting just to make sure we've considered enough scenarios. We couldn't come to a strong conclusion either way so decided to raise an issue here.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1929	'TransportExtensions<AzureServiceBusTransport>' does not contain a definition for 'Sanitization' and the best extension method overload 'AzureServiceBusTransportExtensions.Sanitization(TransportExtensions<AzureServiceBusTransport>)' requires a receiver of type 'TransportExtensions<AzureServiceBusTransport>'	ServiceControl.AcceptanceTests	C:\p\ServiceControl\src\ServiceControl.AcceptanceTests\ConfigureEndpointAzureServiceBusForwardingTopologyTransport.cs	17	Active
Error	CS0433	The type 'AzureServiceBusTransport' exists in both 'NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=8.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Transport.AzureServiceBus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'	ServiceControl.AcceptanceTests	C:\p\ServiceControl\src\ServiceControl.AcceptanceTests\ConfigureEndpointAzureServiceBusEndpointTopologyTransport.cs	12	Active
Error	CS1929	'TransportExtensions<AzureServiceBusTransport>' does not contain a definition for 'UseEndpointOrientedTopology' and the best extension method overload 'AzureServiceBusTransportExtensions.UseEndpointOrientedTopology(TransportExtensions<AzureServiceBusTransport>)' requires a receiver of type 'TransportExtensions<AzureServiceBusTransport>'	ServiceControl.AcceptanceTests	C:\p\ServiceControl\src\ServiceControl.AcceptanceTests\ConfigureEndpointAzureServiceBusEndpointTopologyTransport.cs	16	Active
Error	CS1929	'TransportExtensions<AzureServiceBusTransport>' does not contain a definition for 'Sanitization' and the best extension method overload 'AzureServiceBusTransportExtensions.Sanitization(TransportExtensions<AzureServiceBusTransport>)' requires a receiver of type 'TransportExtensions<AzureServiceBusTransport>'	ServiceControl.AcceptanceTests	C:\p\ServiceControl\src\ServiceControl.AcceptanceTests\ConfigureEndpointAzureServiceBusEndpointTopologyTransport.cs	25	Active
Error	CS0246	The type or namespace name 'Engine' could not be found (are you missing a using directive or an assembly reference?)	ServiceControlInstaller.CustomActions.UnitTests	C:\p\ServiceControl\src\ServiceControlInstaller.CustomActions.UnitTests\Logger.cs	4	Active
Error	CS0246	The type or namespace name 'ILogging' could not be found (are you missing a using directive or an assembly reference?)	ServiceControlInstaller.CustomActions.UnitTests	C:\p\ServiceControl\src\ServiceControlInstaller.CustomActions.UnitTests\Logger.cs	6	Active
Error	CS0433	The type 'AzureServiceBusTransport' exists in both 'NServiceBus.Azure.Transports.WindowsAzureServiceBus, Version=8.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Transport.AzureServiceBus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'	ServiceControl.AcceptanceTests	C:\p\ServiceControl\src\ServiceControl.AcceptanceTests\ConfigureEndpointAzureServiceBusForwardingTopologyTransport.cs	12	Active
Error	CS1929	'TransportExtensions<AzureServiceBusTransport>' does not contain a definition for 'UseForwardingTopology' and the best extension method overload 'AzureServiceBusTransportExtensions.UseForwardingTopology(TransportExtensions<AzureServiceBusTransport>)' requires a receiver of type 'TransportExtensions<AzureServiceBusTransport>'	ServiceControl.AcceptanceTests	C:\p\ServiceControl\src\ServiceControl.AcceptanceTests\ConfigureEndpointAzureServiceBusForwardingTopologyTransport.cs	13	Active
```

Potentially required workaround

https://github.com/NuGet/Home/issues/4989

**Comment by bording** [comment]
In general, the use case for referencing both of the transports in a single project seems like an edge case that isn't likely to be hit by customers.

@kbaley It is actually possible to handle this scenario in in a project if you need it, though it does rely on a rather obscure `extern alias` feature.

**Comment by SeanFeldman** [comment]
> In general, the use case for referencing both of the transports in a single project seems like an edge case that isn't likely to be hit by customers.

This is what we've discussed when ruled out the option of using both transports at the same time. I've asked to come up with an edge case that can be a real scenario to validate it could be addressed by `extern alias` workaround.

We also need to keep in mind that our long term objective is transition everyone off ASB to ASBS.

**Comment by kbaley** [comment]
The aforementioned workaround does work for the scenario that led to this issue though not without its own angst. It's not trivial but it's not terrible either and I think would be considered reasonable for edge cases. In the absence of other scenarios where this might come up, I suggest we close this.

**Comment by SeanFeldman** [comment]
Agreed

**Comment by SeanFeldman** [comment]
Closing this one as there's a workaround that can be applied.

**Comment by danielmarbach** [comment]
For completeness reasons:

When code analysis such as ReSharper is used it might be required to mark the source files as compiler generated by adding the CompilerGenerated attribute or rename the files to comply with inspection exclusion file patterns like `.g.cs` or `.Generated.cs`
