### ISSUE TITLE
Message too large for batch and then not sent

### ISSUE THREAD

**Issue by peterhutgasunie** [Particular/NServiceBus.Transport.AzureServiceBus#1048]
#### Description
Logging showed that:
"Message '4aae1ee3-7fca-432f-9a35-b1f100ae9abe' is too large for the batch '0' and will be sent individually to destination sbq-acc-ctb-shared-external-meteringworker."
But then nothing happened: the message is not sent.

#### Expected behavior
Message is sent and either the message is placed in the Azure Service Bus OR an exception is thrown if the message is too large for the queue.

#### Actual behavior
Nothing happens after reporting that it is too large for the batch.

#### Versions
NServiceBus 9.1.1 
Azure Service Bus transport 4.2.0

### Steps to reproduce

Send message that is larger than batch size (1024KB). Message size configured on the queue does not matter. 

### Relevant log output

```shell
On environment A:
"Message '4aae1ee3-7fca-432f-9a35-b1f100ae9abe' is too large for the batch '0' and will be sent individually to destination sbq-acc-ctb-shared-external-meteringworker."
and then nothing.
```

#### Workarounds
None.

#### Possible solutions
Looking at the code I suspect an issue in MessageDispatcher.
https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/master/src/Transport/Sending/MessageDispatcher.cs#L134

On line 134 a Task to execute DispatchBatchForDestination is added to dispatchTasks and passes the list messagesTooLargeToBeBatched into it.
Then on line 136 that list is iterated immediately, but I think the DispatchBatchForDestination may not have been executed then yet, so if a message is too large it will only be added to the list after the iteration on line 136, with an empty list, has already happened.

Could this be what is happening? I also see errors that the message is sent and then fails because the message is too large for the configured queue. Not sure how that can happen, as I would suspect it always loses the messages, so maybe something is missing in my logic.

**Comment by DavidBoike** [comment]
Will be released as 4.2.1.

**Comment by DavidBoike** [comment]
@peterhutgasunie 4.2.1 has been released.

**Comment by danielmarbach** [comment]
Following through with a simplification of the dispatcher https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/1052
