### ISSUE TITLE
Use Managed Service Identity to access Azure Service Bus 

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.Transport.AzureServiceBus#139]
It would be nice to connect to a Azure Service Bus namespace without providing a connection string.

This should be possible by using Managed Service Identity

**Comment by SeanFeldman** [comment]
You can already do that by modifying the connection string to the following format: 
`Endpoint=sb://<namespace>.servicebus.windows.net/;Authentication=Managed Identity`.

**Comment by JSCProjects** [comment]
Really nice!!!!

**Comment by SeanFeldman** [comment]
Indeed. It's baked into the ASB SDK.
