### ISSUE TITLE
Ability to set the LockDuration of a Queue

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.Transport.AzureServiceBus#14]
In the other client of Azure Service Bus it's possible to set the LockDuration, it would be nice to configure this in this transport.

**Comment by SeanFeldman** [comment]
The transpot is configuring the default for reliability and the most common use-case.
One of the reasons we chose 5 mins `LockDuration` is due to the fact there was a lot of confusion about ASB's default (30 seconds), `Prefetch`, and `AutoLockRenewal`.

Most customers want to process their messages w/o worry for lock expiration. We've defined the default values for `LockDuration` and `Prefetch` to ensure no messages are losing their locks when processing is lengthier than 30 seconds. If processing is successful, messages will be completed. In case messages failing processing, they will go through recoverability. Only when there's an abnormal shutdown behaviour (endpoint is crushing) it would take up-to 5 minutes for a message to re-appear.

Additionally, the transport creates the topology, but does not update it. If you wish to reconfigure your endpoint's queue to have a shorter `LockDuration` time, you could. The question I'll be asking what would you gain from it?

**Comment by JSCProjects** [comment]
Sean,

Thanx didn’t know that that was the default behaviour. I thought it was 30 sec and wanted it to 65 sec for HttpTimeouts, 300sec is good enough for me!

Perhaps you could add this documentation onto the particular transport page.

Greetz,

Joey Chömpff


________________________________
Van: Sean Feldman <notifications@github.com>
Verzonden: maandag, september 3, 2018 7:52 PM
Aan: Particular/NServiceBus.Transport.AzureServiceBus
CC: JSC Projects; Author
Onderwerp: Re: [Particular/NServiceBus.Transport.AzureServiceBus] Ability to set the LockDuration of a Queue (#14)


The transpot is configuring the default for reliability and the most common use-case.
One of the reasons we chose 5 mins LockDuration is due to the fact there was a lot of confusion about ASB's default (30 seconds), Prefetch, and AutoLockRenewal.

Most customers want to process their messages w/o worry for lock expiration. We've defined the default values for LockDuration and Prefetch to ensure no messages are losing their locks when processing is lengthier than 30 seconds. If processing is successful, messages will be completed. In case messages failing processing, they will go through recoverability. Only when there's an abnormal shutdown behaviour (endpoint is crushing) it would take up-to 5 minutes for a message to re-appear.

Additionally, the transport creates the topology, but does not update it. If you wish to reconfigure your endpoint's queue to have a shorter LockDuration time, you could. The question I'll be asking what would you gain from it?

**Comment by SeanFeldman** [comment]
Thank you @JSCProjects 

> Perhaps you could add this documentation onto the particular transport page.

Let me ask the reason you think this information would be important to document?
Assuming you'd never use the old ASB transport and never ran into a lost lock token issue, why would it be important for you to know?

**Comment by JSCProjects** [comment]
Yeah but I’m migrating from the old transport so I’m used to set these props 😁


________________________________
Van: Sean Feldman <notifications@github.com>
Verzonden: maandag, september 3, 2018 8:00 PM
Aan: Particular/NServiceBus.Transport.AzureServiceBus
CC: JSC Projects; Mention
Onderwerp: Re: [Particular/NServiceBus.Transport.AzureServiceBus] Ability to set the LockDuration of a Queue (#14)


Thank you @JSCProjects<https://github.com/JSCProjects>

Perhaps you could add this documentation onto the particular transport page.

Let me ask the reason you think this information would be important to document?
Assuming you'd never use the old ASB transport and never ran into a lost lock token issue, why would it be important for you to know?

**Comment by SeanFeldman** [comment]
So what I hear is that only because you're migrating from the old ASB tranport, you're concerned about this setting. Is that it?

**Comment by JSCProjects** [comment]
Yup 😁


________________________________
Van: Sean Feldman <notifications@github.com>
Verzonden: maandag, september 3, 2018 8:57 PM
Aan: Particular/NServiceBus.Transport.AzureServiceBus
CC: JSC Projects; Mention
Onderwerp: Re: [Particular/NServiceBus.Transport.AzureServiceBus] Ability to set the LockDuration of a Queue (#14)


So what I hear is that only because you're migrating from the old ASB tranport, you're concerned about this setting. Is that it?

**Comment by SeanFeldman** [comment]
Would it help to see an [upgrade guide](https://docs.particular.net/transports/upgrades/) from ASB to ASBS, containing a sections about settings that are not configurable in the new transport and explanation similar to what I've provided here?

**Comment by JSCProjects** [comment]
Yeah that would be great!


________________________________
Van: Sean Feldman <notifications@github.com>
Verzonden: maandag, september 3, 2018 9:02 PM
Aan: Particular/NServiceBus.Transport.AzureServiceBus
CC: JSC Projects; Mention
Onderwerp: Re: [Particular/NServiceBus.Transport.AzureServiceBus] Ability to set the LockDuration of a Queue (#14)


Would it help to see an upgrade guide<https://docs.particular.net/transports/upgrades/> from ASB to ASBS, containing a sections about settings that are not configurable in the new transport and explanation similar to what I've provided here?

**Comment by SeanFeldman** [comment]
👍 I'll keep this issue opened until we have something in place.
Thank you for the feedback @JSCProjects

**Comment by mikeminutillo** [comment]
Just had a LiveChat with a customer that was looking for a way to extend the Lock Duration beyond 5 mins. They did not stick around long enough to explain what they were doing.

**Comment by SeanFeldman** [comment]
@mikeminutillo I'd suggest to send them to this [comment](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/14#issuecomment-418169255) to find out why we decided not to provide support for `AutoLockRenewal`.

**Comment by LarsCelie** [comment]
@SeanFeldman You mention you do not provide support for `AutoLockRenewal` and that 5 minutes should be sufficient. What if you're processing large files with databus and it takes 6 minutes to process it? It would throw a MessageLockLostException and retry and fail again because it's still not fast enough.

**Comment by JSCProjects** [comment]
Hi Lars,

That’s because the maximum lock timout of a queue in Azure Service Bus is 5 minutes

[cid:image001.png@01D577A4.BA46C640]

Met vriendelijke groeten / Kind regards,

Joey Chömpff

[http://www.jsc-projects.nl/userfiles/newlogo50percent.png]

JSC Projects
Blankena 16
8103 JC Raalte
the Netherlands

Telefoon: 06-150 12 458
E-Mail: mail@jsc-projects.nl<mailto:mail@jsc-projects.nl>
Internet: http://www.jsc-projects.nl<http://www.jsc-projects.nl/>
Twitter: @JSCProjects<http://twitter.com/#!/jscprojects>
LinkedIn: jchompff<https://www.linkedin.com/in/jchompff/>
KvK te Zwolle: 08178187
BTW: NL105372055B01
Bankrekening: NL78 RABO 0110 2858 08

**Comment by amolenk** [comment]
I think there are two important points here:
1) Having a default LockDuration of 5min. I agree with @SeanFeldman that 5 minutes is a good default value to have.
2) Having the ability to extend the lock beyond the 5min. This would be necessary for scenarios such as described by @LarsCelie. Azure Service Bus supports this with the RenewLockAsync method (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.renewlockasync?view=azure-dotnet). It would be great if NServiceBus could simply keep renewing the lock while the handler is processing the message. An alternative would be to have some way to call the method ourselves, but that would kinda break the abstraction.

**Comment by dvdstelt** [comment]
The timings are described in the documentation for this sample: https://docs.particular.net/transports/azure-service-bus/legacy/message-lock-renewal

As @SeanFeldman mentions, default lock timeout is 30 seconds, it renews for 5 minutes. Not longer. So we do renew the lock, but not for too long, for reasons. Do you have a specific example where you'd want longer than 5 minutes @amolenk ? Can also discuss this in another channel, if you wish.

**Comment by SeanFeldman** [comment]
> As @SeanFeldman mentions, default lock timeout is 30 seconds, it renews for 5 minutes.

The default `MaxLockDuration` is set to the maximum **5 minutes** (rationale is described [here](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/14#issuecomment-418169255)).

This transport **does not renew the lock** as the operation is not guaranteed and can fail. `RenewLockAsync()` of the ASB client is a client-side initiated operation that can and occasionally will fail, leading to surprises as to why one out of N messages got re-processed more than once.

For scenarios when lengthy processing is required, the sample @dvdstelt has linked to is the approach we recommend to take.

**Comment by SeanFeldman** [comment]
Will be addressed by the documentation
