### ISSUE TITLE
Documentation Issue: NuGet package name isn't documented

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.Transport.AzureServiceBus#15]
It would be nice to have the new NuGet package name: "NServiceBus.Transport.AzureServiceBus" documented.

**Comment by SeanFeldman** [comment]
@JSCProjects it is alrady appearing in the documentation, similar to [this](https://docs.particular.net/transports/azure-service-bus-netstandard/)

![image](https://user-images.githubusercontent.com/1309622/44998102-35496300-af70-11e8-978f-91696d63cd5c.png)

Also, sample pages expose it

![image](https://user-images.githubusercontent.com/1309622/44998131-66299800-af70-11e8-95dd-2c3a0cdac83a.png)

Let me know if this is what you were looking for 🙂

**Comment by JSCProjects** [comment]
Yeah again you’re right didn’t saw that on the documentation🤐


________________________________
Van: Sean Feldman <notifications@github.com>
Verzonden: maandag, september 3, 2018 7:57 PM
Aan: Particular/NServiceBus.Transport.AzureServiceBus
CC: JSC Projects; Mention
Onderwerp: Re: [Particular/NServiceBus.Transport.AzureServiceBus] Documentation Issue: NuGet package name isn't documented (#15)


@JSCProjects<https://github.com/JSCProjects> it is alrady appearing in the documentation, similar to this<https://docs.particular.net/transports/azure-service-bus-netstandard/>

[image]<https://user-images.githubusercontent.com/1309622/44998102-35496300-af70-11e8-978f-91696d63cd5c.png>

Also, sample pages expose it

[image]<https://user-images.githubusercontent.com/1309622/44998131-66299800-af70-11e8-95dd-2c3a0cdac83a.png>

Let me know if this is what you were looking for 🙂

**Comment by SeanFeldman** [comment]
I'm not right, you're not wrong. We're human 😃 
No worries. Thanks for the feedback @JSCProjects
