### ISSUE TITLE
Async publish creates a batch?

### ISSUE THREAD

**Issue by Avalaxy** [Particular/NServiceBus.Transport.AzureServiceBus#158]
**Describe the bug**
I'm trying to publish a bunch of messages in a loop (using await context.Publish()). This seems to go well (the loop finishes and the end of my routine is reached), but the event handler is never reached. Before the messages can be handled, I get the following error (this is using Azure Service Bus):

``Immediate Retry is going to retry message 'a368d838-8208-42a2-8933-ac1c00f5b65c' because of an exception: (NServiceBus.RecoverabilityExecutor)
Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot send more than 100 messages in a single transaction. TrackingId:9a30ca8500007d4c0141ade55f3d3d2d_G15_B3, SystemTracker:leoncullens:Queue:proovr.itops.proxyclick, Timestamp:2020-08-19T14:54:57
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.Invoke(ITransportReceiveContext context, Func`2 next)
   at Proovr.Server.Hosting.NServiceBus.AttachTransportContextBehavior.Invoke(ITransportReceiveContext context, Func`1 next) in C:\Users\LeonCullens\source\repos\proovr-server\Hosting\NServiceBus\AttachTransportContextBehavior.cs:line 25
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.InnerProcessMessage(Task`1 receiveTask)``

The messages that I'm publishing are some very simple classes that have a List of sub objects (at the moment I'm testing with 20 sub objects that are in turn also pretty simple (only 4 string properties).

Is ASB doing any batching under water that results in this error? Is there something else that could be going on? 

**To Reproduce**

**Expected behavior**
I just hoped it would work.

**Versions:**
 - NuGet package: NserviceBus 7, NserviceBus.Transport.AzureServiceBus 1.5.0, 
 - OS: Windows 10 latest
 - .NET Core 3.1

**Additional context**

**Comment by SeanFeldman** [comment]
Without seen the code, this is likely happening as a result of publishing more than 100 events from a handler that is by default batching the operations and atomically tries to execute along with the completion of the incoming message that triggered the handler. By default, the ASB transport is using [`SendsAtomicWithReceive`](https://docs.particular.net/transports/transactions#transactions-transport-transaction-sends-atomic-with-receive) transport transaction mode that enforces this behaviour. The individual sends/publishes are batched internally by NServiceBus and handed over to the underlying ASB SDK to ensure those are executed only if the handler has completed successfully.

If you need to send more than 100 messages (publish events in your case), there a few options:
1. Break down sends into batches of no more than 100 - would require a change to how you handle the incoming message and issue publishing intent command.
1. Use [immediate dispatch](https://docs.particular.net/nservicebus/messaging/send-a-message#dispatching-a-message-immediately). Important to highlight that the side effect of this approach could be ghost messages when the handler or completion of the incoming message fails.
1. Lower the transport transaction mode to `ReceiveOnly`. Has a similar impact as the previous option.

Does this help with your question?

**Comment by SeanFeldman** [comment]
@Avalaxy I'm going to close the case. In case you want to follow up, please let know.
