### ISSUE TITLE
Improve error handling when message property exceeds max size

### ISSUE THREAD

**Issue by amolenk** [Particular/NServiceBus.Transport.AzureServiceBus#171]
**Is your feature request related to a problem? Please describe.**
We had an issue in a production system where a message went in a retry loop. We found the root cause to be a message property that exceeded the maximum size (it was a particularly large Exception stack trace stored in the message property).
It took us a while to figure this out because the error message is not really clear.

Repro:
``` csharp
try
{
    string messageBody = "Hello, world";
    var message = new Message(Encoding.UTF8.GetBytes(messageBody));
    message.UserProperties["TooLarge"] = string.Empty.PadRight(32786, '.');

    await queueClient.SendAsync(message);
}
catch (Exception exception)
{
    Console.WriteLine($"{DateTime.Now} :: Exception: {exception.Message}");
}
```

The exception caught is:
``` 
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:ab4341ef-ee3e-4015-960f-1c99b1bbbd89, TrackingId:3374c6ae0000930c009bb77a5f69fca9_G9_B2, SystemTracker:unknownerrorrepro:Queue:error, Timestamp:2020-09-22T13:31:57
```

I did some debugging with the SDK, and what happens is that an AMQP rejection with code 37 is received from the server. This result cannot be mapped to an Error object which is why a `new ServiceBusException(true, "Unknown error.")` is thrown.

**Describe the solution you'd like**
The SDK should throw an Exception before publishing the message with clear information on why the message cannot be published.

**Comment by amolenk** [comment]
Damn, wrong repo ;-) This should go to the Azure Service Bus SDK.

**Comment by SeanFeldman** [comment]
@amolenk, no problem. Just an FYI, this is the intended behaviour of the SDK. The size limit is [documented](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas) as:
> Maximum message size: 256 KB for Standard tier, 1 MB for Premium tier.

The premium tier is planned to have support for up-to 100MB.

**Comment by NitinM3** [comment]
> @amolenk, no problem. Just an FYI, this is the intended behaviour of the SDK. The size limit is [documented](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas) as:
> 
> > Maximum message size: 256 KB for Standard tier, 1 MB for Premium tier.
> 
> The premium tier is planned to have support for up-to 100MB.

Do you know when it is planned to have support for up-to 100MB? Any reference document?

**Comment by SeanFeldman** [comment]
> Do you know when it is planned to have support for up-to 100MB? Any reference document?

It's been shared as a planned feature and mentioned on social media. JMS 2.0 supports large files and given the effort to bring parity between ASB and JMS 2.0 Microsoft will be adding it.
