### ISSUE TITLE
Endpoint in endless loop when stacktrace is to long

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.Transport.AzureServiceBus#172]
When we try to handle a message which contains a lot of errors and we throw an exception with a too long message and stacktrace the endpoint is coming in an endless loop, because endpoint trues to move the message to the error queue (with all (too large) headers). Azure Service Bus will gives an AMQP 37 error which is mapped on Unknown error and then the NServicebus does an endless retry.

NServicebus protects itselfs against to long exception messages, but the same thing also can happen with a stacktrace.

```
headers["NServiceBus.ExceptionInfo.Message"] = e.GetMessage().Truncate(16384);
headers["NServiceBus.ExceptionInfo.StackTrace"] = e.ToString();
```

It think the same truncate must be done with the stacktrace and maybe we can better use e.StackTrace

**Comment by SeanFeldman** [comment]
@JSCProjects, NServiceBus does this when handling failed messages. The code you've referred to is coming from the core project, not the transport. Did you mean to raise this issue in the https://github.com/Particular/NServiceBus repo?

**Comment by JSCProjects** [comment]
Recreated it on the NServiceBus repo

**Comment by SeanFeldman** [comment]
Replaced with https://github.com/Particular/NServiceBus/issues/5764
