### ISSUE TITLE
Support pub/sub for multiple instances

### ISSUE THREAD

**Issue by AlexandruRus23** [Particular/NServiceBus.Transport.AzureServiceBus#201]
I have not seen this being requested before. Hoping I'm posting this in the right repo.

I'm currently trying to implement a solution for changing the state inside an ASP.NET Core 3 app by using NServiceBus messages and Azure Service Bus transport. Using Pub/Sub, the endpoint inside the webhost will generate a topic subscription with the endpoint's name. I did not find a way to add a variation to this to enable multiple instances (only the 50+ characters transformation but this seems like a strange workaround). If I change the name of each endpoint on startup, I seem to lose the ability to listen on a Service Bus Queue (in a competing consumer scenario on the same queue).

I think some sort of mechanism to support configuring the subscription name that is used is enough. Although the ability to do a clean-up of the resources that the endpoint has generated would also come in handy. 

I have not looked into other transports as of yet. I may be able to handle it only being able to consume events, but I found the limitation a bit strange.

**Comment by SeanFeldman** [comment]
@AlexandruRus23, this is not a limitation NServiceBus imposes. This is the [Azure Service Bus constraint](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas):

> Maximum size of any messaging entity name: namespace, subscription, or subscription rule

You're welcome to let the Azure Service Bus team know that these inconsistent name length constraints are not to your satisfaction and upvote [an existing issue](https://github.com/Azure/azure-service-bus/issues/257) about that.

Have you looked into the [transport configuration documentation](https://docs.particular.net/transports/azure-service-bus/configuration#entity-creation)? You've got:
- `SubscriptionNameShortener` to handle subscription names where the endpoint name exceeds the maximum length.
- `RuleNameShortener` to handle rule names where event full name exceeds the maximum length.

Let me know if that unblocks you as you should be able to use the name that you need for your endpoints while remaining compliant with the ASB subscription and rule name constraints.

**Comment by AlexandruRus23** [comment]
@SeanFeldman thank you for the quick answer. 

I basically want to have multiple instances of an endpoint in which all of them listen on 1 service bus queue (competing consumer), but have different subscriptions under one service bus topic (for pub/sub). I did notice SubscriptionNameShortener but to make it work I'll have to artificially generate a name more than 50 characters long in order for the func to kick in and rename my subscription.

I hope this makes sense.

**Comment by SeanFeldman** [comment]
@AlexandruRus23, to be honest, I'm not sure what is it that you're trying to achieve. 

> I basically want to have multiple instances of an endpoint in which all of them listen on 1 service bus queue (competing consumer), but have different subscriptions under one service bus topic (for pub/sub).

That's not how competing consumer pattern works. If your logical endpoint is scaled out, all physical instances of that logical endpoint will be receiving from the same queue/subscription. An event the logical endpoint is subscribed to should not be duplicated for each physical instance, rather handled by a single instance. The subscription name shortener allows you to shorten the name of any subscription/rule in an automate fashion by plugin your own shortening logic.

To understand better what you're trying to do or what the difficulty is, I would suggest opening a support case at https://particular.net/support, linking to this GitHub issue for the details. Keeping this issue open until there's an update that can be shared here.

**Comment by SeanFeldman** [comment]
@AlexandruRus23, did you get the answers you were looking for or contacted the support?

**Comment by SeanFeldman** [comment]
@AlexandruRus23, I'm assuming you've got the answer you were looking for.
Going to close it. If there are any follow-up questions, please comment here or [send a support request](https://particular.net/support). Thank you.
