### ISSUE TITLE
We should add a net461 target.

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.Transport.AzureServiceBus#21]
Even though the Azure client is currently only `netstandard2.0`, we should consider going ahead and multi-targeting to `net461` as well, to put us closer to doing the right thing around .NET Standard 2.0 support for `net461` - `net471`.

**Comment by SeanFeldman** [comment]
Agreed. ASB team will be adding multi-targeting back. I had to do the same for the [Attachments plugin](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/pull/66) and they will do the same in the next release.

**Comment by bording** [comment]
No reason to also have a `net471` target.
