### ISSUE TITLE
Subscription rules generated with CLI are ignored. "Extra" rules created during Startup. Could push up against ASB rule number limitations.

### ISSUE THREAD

**Issue by seankearney** [Particular/NServiceBus.Transport.AzureServiceBus#213]
**Describe the issue**

Using the CLI, we've created subscription rules with short names (`-r` option). When we start the endpoint we see extra rules being created. This can become a problem when the number of rules grows to 1,000 and then the Transport will start creating duplicate rules putting us at the 2,000 limit.

**To Reproduce**

For our development environments we use the NSB CLI to generate subscriptions, rules, etc... 

In many cases we have type names >50 characters, which requires us to have a custom, shorter, rule name. Additionally, in order to have a consistent naming scheme we've applied our custom rule name approach to all of our rules. We have this "RuleNameShortner" configured on the Transport that matches these names we've created.

Examples:

```
asb-transport endpoint subscribe EndpointName MyCompanyName.MyProductName.MyFeatureName.MyClassName -r MyClassName -c "<connection-string>"
asb-transport endpoint subscribe EndpointName MyCompanyName.MyProductName.MyFeatureName.Short -r Short -c "<connection-string>"
```

The above example gives us two rules and both of them are named with the name of the class, even though the `Short` class doesn't require a shortner.

The problem pops up when I start my endpoint. The endpoint will end up creating a new rule for me named `MyCompanyName.MyProductName.MyFeatureName.Short`. It would seem that the "Rule Name Shortner" isn't applied on names that don't need to be shortened. This makes sense, however it seems to conflict with ability to use CLI to create rules with custom names.

**Expected behavior**

Ideally, I'd like to be able to create my topology with CLI (or ARM templates) as desired and have the Transport use what was configured and not create extra rules.

**Versions:**
 - NuGet package: 
   - NServiceBus.AzureFunctions.ServiceBus 0.3.0
   - NServiceBus.Transport.AzureSErviceBus 1.5.0
 - OS: Windows (Azure Function)
 - .NET Core 3.1

**Comment by SeanFeldman** [comment]
The same issue impacts subscription names that exceed the maximum length. While CLI will use the short name provided via parameters, `SubscriptionManager` will ignore if the name is not exceeding the maximum length allowed for subscriptions.

**Comment by SeanFeldman** [comment]
A new minor release 1.8.0 has been published.
Please refer to the [announcement](https://discuss.particular.net/t/nservicebus-transport-azureservicebus-1-8-0-minor-release-available/2223) for more details.
