### ISSUE TITLE
Change warning to not throw when larger than 64kb, instead 256kb/1MB?

### ISSUE THREAD

**Issue by joshuataylor** [Particular/NServiceBus.Transport.AzureServiceBus#26]
**Is your feature request related to a problem? Please describe.**
When sending a large message, an error is thrown when above 64kb, but Azure Service Bus supports 256kb as a maximum for standard (see https://azure.microsoft.com/en-au/pricing/details/service-bus/).

```
The total size of the FooEvent, Foo, Version=1.1.8.0, Culture=neutral, PublicKeyToken=null' message body (92801 bytes) plus headers (803 bytes) is larger than 64 KB and will not be supported on some production transports. Consider using the NServiceBus DataBus or the claim check pattern to avoid messages with a large payload. Use 'EndpointConfiguration.UseTransport().NoPayloadSizeRestriction()' to disable this check and proceed with the current message size.
```

**Describe the solution you'd like**
Discussion around when this should be thrown.

**Describe alternatives you've considered**
Databus :)

**Comment by SeanFeldman** [comment]
@joshuataylor standard tier supports up-to 256KB.
We'll look into this issue, thank you for reporting it.

**Comment by joshuataylor** [comment]
Sorry, meant maximum, not minimum. Fixed in original.

Thanks!

**Comment by SeanFeldman** [comment]
@joshuataylor are you sure Azure Service Bus transport is used? This exception is [thrown by `LearningTransport`](https://github.com/Particular/NServiceBus/blob/410746a912b4c52dd3b30d2314cd2f811ba196b4/src/NServiceBus.Core/Transports/Learning/LearningTransportDispatcher.cs#L121). Azure Service Bus does not throw this exception.

**Comment by SeanFeldman** [comment]
@joshuataylor I'm going to close this issue. If you have a repro to demonstrate ASB transport is causing it, please re-open.
