### ISSUE TITLE
.NET Core global tool includes entity name it couldn't create

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Transport.AzureServiceBus#30]
It would have been helpful to include the name of the entity that couldn't be created

1. queue: https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/29#discussion-diff-239436705R18
1. topic: https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/29#discussion-diff-239436749R27
1. subscription: https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/29#discussion-diff-239436805R32

**Comment by danielmarbach** [comment]
Fixed with https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/84
