### ISSUE TITLE
asb-transport with existing queue, topic or subscription it outputs a wrong log

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.Transport.AzureServiceBus#308]
When executing asb-transport and queue, topic or subscription exists it outputs  a wrong log line

![image](https://user-images.githubusercontent.com/19533149/113139334-455c7880-9227-11eb-8965-769ea042cdec.png)

**Comment by SeanFeldman** [comment]
@JSCProjects what version of the transport/tool are you using?

**Comment by JSCProjects** [comment]
I'm running also 
`dotnet tool install --tool-path tools --ignore-failed-sources NServiceBus.Transport.AzureServiceBus.CommandLine`

so I would think latest version

**Comment by SeanFeldman** [comment]
@JSCProjects something doesn't look right here. The incorrect messages were [fixed](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/commit/31f2cc97b10937154640e7f01fca6de6bcb514a0) and released in https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/releases/tag/1.9.0.

Could you run the tool with the following command to see if it's the latest indeed?
```
dotnet tool list --global
```

You should see `NServiceBus.Transport.AzureServiceBus.CommandLine` in the list with version 1.9. If it's a different version, you'd need to update the [`tools` location](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/308#issuecomment-811907572) where your command is taking it from.

```
Package Id                                             Version         Commands
----------------------------------------------------------------------------------------
nservicebus.transport.azureservicebus.commandline      1.9.0           asb-transport
```

If after that you still experience this issue, please raise a support case as something is really off here. Thank you.

**Comment by JSCProjects** [comment]
@SeanFeldman ok locally it's still on 1.5.0 even when I run dotnet tool install -g --ignore-failed-sources NServiceBus.Transport.AzureServiceBus.CommandLine

**Comment by SeanFeldman** [comment]
@JSCProjects you need to be on 1.9.0 to see the fixed messages. Once you can confirm, the issue could be closed.

**Comment by JSCProjects** [comment]
After forcing an update the error was gone
