### ISSUE TITLE
Unable to receive message with .NET 5 running in container

### ISSUE THREAD

**Issue by RiaanVR** [Particular/NServiceBus.Transport.AzureServiceBus#309]
**Describe the bug**
System.InvalidOperationException: Operation is not valid due to the current state of the object., this happens from internally within the `Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync` 

**To Reproduce**
Build a simple endpoint with .NET 5, package it up as a container with the base image `mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim` try starting the container

**Expected behavior**
Startup and process any message where the subscription exists and there is a handler within the running app.

**Versions:**
 - NuGet package: 
 ```
 <PackageReference Include="NServiceBus" Version="7.4.6" />
 <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="1.9.0" />
 ```
 - OS: `mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim`
 - .NET Version `net5`

**Additional context**
- Code repro
- Screenshot
![image](https://user-images.githubusercontent.com/9514231/113269685-fd962980-92d8-11eb-918a-b9b4d41bcdfd.png)

**Comment by RiaanVR** [comment]
I just upgraded to these NuGet packages and published again and seems fine...

**Comment by danielmarbach** [comment]
@RiaanVR Thanks for opening such a detailed error report. Glad it was resolved. Should you run into issues again let us know and we will see what we can do.
