### ISSUE TITLE
Custom retries for transient errors

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Transport.AzureServiceBus#33]
Legacy ASB transport applied custom retries for ASB operations that have failed with transient errors. This is a common practice for Azure Service Bus to address connectivity and broker issues that can be fixed by retrying w/o necessarily going through NServiceBus immediate retries first that could be consumed quickly.
This was implemented by [`TaskWithRetryExtensions.RetryOnThrottleAsync`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/7e5241f910158a1d97058a6039fa9a389a0b3f81/src/Transport/Connectivity/TaskWithRetryExtensions.cs#L10) when we were [sending messages out](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/7a7870a8edf94a74680d5f6c50514bd93a65842a/src/Transport/Sending/OutgoingBatchRouter.cs#L204).

The new transport will not do so. `RetryPolicy` built into the new client is currently broken (https://github.com/Azure/azure-service-bus-dotnet/issues/615) in a way that retries are applied when shouldn't (ambient transaction is found), leaving the new transport w/o custom retries.

Question is - should we reintroduce custom retries similar to the legacy ASB transport, or solely rely on the NServiceBus retries when transient errors are encountered.

**Comment by bording** [comment]
One thing to consider here is that retrying failed sends isn't something that is only relevant/valuable for ASB. This sounds like a feature that should be implemented core and then everyone benefits from it.

**Comment by SeanFeldman** [comment]
With the upcoming ASB SDK v7 (track 2) the transport will be updated to use the new SDK which contains multiple improvements, including retries for transient errors.
