### ISSUE TITLE
The transport fails to properly suppress ambient transactions

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Transport.AzureServiceBus#42]
## Who's affected

Anyone using Gateway feature or sending messages within a transaction scope with isolation level other than `Serializable`.

## Symptoms

When sending messages within a transaction scope, `System.InvalidOperationException` exception is thrown with the following message: "The only supported IsolationLevel is Serializable".

## Original issue

Using Gateway with the transport. Gateway uses transport's `IDispatchMessages` implementation and wraps the send operation in a transaction scope using [isolation level `ReadCommitted`](https://github.com/Particular/NServiceBus.Gateway/blob/ffc54fa297019b194e908aa29ad02d5366a30896/src/NServiceBus.Gateway/GatewayTransaction.cs#L25). When an endpoint is configured to use `SendsAtomicWithReceive` transport transaction mode, outgoing messages are sent using `DispatchConsistency.Default`. The transport [does not suppress scope](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/003ffad11ca7debc81e85e6260b9804403cd13d7/src/Transport/Sending/MessageDispatcher.cs#L93-L95) for `DispatchConsistency.Default`, but only for `DispatchConsistency.Isolated`.

In this scenario, messages are sent using `DispatchConsistency.Default`, but there's not transaction scope to use and any other ambient transaction (such as Gateway's) should be suppressed.

**Comment by SzymonPobiega** [comment]
I'd say this is:
 * moderate - because message won't be send through the gateway and therefor not processed on time
 * isolated - to be affected users have to use a brand new transport and a component of the pletform that is infrequently used
That means *next in line*

@WojcikMike do you agree?
