### ISSUE TITLE
Send-only endpoint does not create the publish Topic if it does not exist

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Transport.AzureServiceBus#44]
## Who's affected

Anyone using pub/sub in one of the following scenarios:
1. The Subscriber has never executed and the publisher run firs w/o installers enabled.
1. The subscribers has never executed and the publisher run as send-only endpoint.

## Symptoms

Publisher throws an exception when trying to publish an event.

## Details

Topic for published events is created along with queues. If an endpoint is either send-only or installers have been disabled, queue creation will not take place. Subsequently, the topic won't be created either. In case subscribers have not executed, it will mean there will be no topic to publish events to and the publisher will throw an exception.

This is only a problem that can occur on a clean namespace depending on the order of starting the endpoints the first time (rare edge case)

## Original issue

Raised on the public forum [here](https://discuss.particular.net/t/how-do-i-set-the-queue-and-topic-creation-topology-when-using-azure-service-bus-transport-with-net-core/931).

## Workarounds

1. Create topic manually.
1. Run any non send-only endpoint that has installers enabled first.
1. Using the [operational scripting tool](https://docs.particular.net/transports/azure-service-bus/operational-scripting) to create the topic

**Comment by SzymonPobiega** [comment]
I'd say this is somewhere between extreme and major because if the affected endpoint is a web frontend endpoint all the requests that result in publishing messages fail and are effectively lost. Scope-wise I'd say it is limited (a single transport is affected). Given the issue has been found not on production I'd propose to classify it as major/limited -> in progress.

**Comment by SzymonPobiega** [comment]
@WojcikMike do you agree?

**Comment by WojcikMike** [comment]
I agree with the clasification

**Comment by SzymonPobiega** [comment]
@SeanFeldman do you know what should be the correct behavior?

**Comment by SeanFeldman** [comment]
The legacy ASB had this behaviour, but arguably, it was the way it was.
For the new transport, endpoints should be able to just publish. Wherever there's a topic or not. This will also be more aligned with broker-based transports such as RabbitMQ that handles this situation.

**Comment by SeanFeldman** [comment]
Fix for this issue will require a breaking change. Therefore we will introduce it in the next **major** release rather than right away as there are viable workarounds. As well as topic creation needs to take place once and once on;y per environment.

When version 2.0.0 is worked on, we'll include the fix for this issue as well.

**Comment by boblangley** [comment]
I am going to relabel this as an improvement instead of a bug. The current functionality is by design (send-only endpoints do not create infrastructure). It would be a new "feature" of the transport to be able to ensure a topic is created in this scenario. This new feature would align with customer expectations and create alignment with other brokered transports as Sean mentioned.

**Comment by danielmarbach** [comment]
This could be implemented in the next major using the new transport seam that clearly separates subscription at startup vs subscription at runtime. For subscription at startup, the behavior could be changed to the following, if there is no manage rights we assume everything is already properly set up and just continue starting. If the endpoint is started with manage rights we will create the topic.

With such a general assumption around least-privilege, we could follow the same pattern for a send-only endpoint.

**Comment by SeanFeldman** [comment]
Was this done in V8?

**Comment by awright18** [comment]
I created a send-only endpoint with installers enabled using v8, which generates the topic if it does not exist.  It doesn't however generate the topic if installers are not enabled.

**Comment by SeanFeldman** [comment]
That should suffice.
