### ISSUE TITLE
AutoSubscribe fails quietly when event name is too long

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.Transport.AzureServiceBus#55]
**Describe the bug**

When event name is too long, autosubscription fails silently.

**To Reproduce**

Create an event with a long name. Subscribe to it. Start both endpoints (publisher and subscriber) and publish the event. Verify that the subscription has not been created but the subscriber endpoint starts successfully.

**Expected behavior**

The subscriber endpoint should fail to start if it is unable to create a subscription.

**Versions:**
 - NuGet package: Unknown
 - OS: Unknown
 - .NET Version Unknown

**Additional context**
Originally raised in a support case (43171).

Events were not being delivered to a particular subscriber. There were no errors reported. When the customer tried to manually subscribe to the message they discovered that the event name was too long. Implementing a name shortening rule allowed the event to be successfully delivered.

**Comment by SeanFeldman** [comment]
This is an exception thrown when running [ASB Send/Reply sample](https://docs.particular.net/samples/azure-service-bus-netstandard/send-reply/) with [`Message1`](https://github.com/Particular/docs.particular.net/blob/6ccaa334f635d57cfa4b59ffab5890372815ee37/samples/azure-service-bus-netstandard/send-reply/ASBS_1/Shared/Message1.cs) converted to an `IEvent` and renamed to `ThisIsAVeryLongNamedEventThatWillEventuallyCauseAzureServiceBusToBlowUp`

![image](https://user-images.githubusercontent.com/1309622/56014206-801f1c00-5cb1-11e9-9fa2-0f6889424bd6.png)

**Comment by mikeminutillo** [comment]
The transport is correctly throwing an exception and the AutoSubscribe feature in NServiceBus is logging it and swallowing it. I'm connecting with the team internally to try and figure out why it does that and if it's something we can change.

**Comment by SeanFeldman** [comment]
For NServiceBus issue, see https://github.com/Particular/NServiceBus/issues/5195
