### ISSUE TITLE
Issue with deserialization

### ISSUE THREAD

**Issue by Samm138** [Particular/NServiceBus.Transport.AzureServiceBus#593]
Hello, we have an issue with receiving messages from Azure Service Bus. Since the messages are provided from third party trough RabbitMQ, Azure service bus handles them in this way and we have no control over this. 

Message gets resolved as ServiceBusReceivedMessage hence AmqpMessageBodyType is always set to Data and this just throws exception because we get the value as AmqpMessageBodyType = Value. Is there any workaround for this or is this?

https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/96d314b1c51e092620ab7f2ee9f886f12290e828/src/Transport/Receiving/MessageExtensions.cs#L48

**Comment by andreasohlund** [comment]
How can we reproduce this?

Perhaps you would be able to copy https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/master/src/AcceptanceTests/Receiving/When_receiving_a_message_from_legacy_asb.cs and modify it so that it blows up in the same way as you're experiencing?

**Comment by WilliamBZA** [comment]
We're closing this as not reproducible. @Samm138 if you're able to provide some more details on how we can reproduce this please reopen this issue with details. You can also reach out to our support team to arrange a call to talk through it if that would be easier.
