### ISSUE TITLE
When using `TokenCredential` validate if connection string only contains the fully qualified namespace

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Transport.AzureServiceBus#604]
When using `TokenCredential` the transport connection string needs to different:

Wrong:

```c#
transport.ConnectionString("Endpoint=sb://[NAMESPACE].servicebus.windows.net/;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]");
```
Correct:

```c#
transport.ConnectionString("[NAMESPACE].servicebus.windows.net");
```

Not doing this results in:

> System.ArgumentException: The value 'Endpoint=sb://my-namespace.servicebus.windows.net/' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace')

See:

- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/588

It is not obvious that this is due to an incorrect connection string.

[The guidance has been updated to clarify how to use TokenCredential](https://github.com/Particular/docs.particular.net/pull/5830) but we can do better.

When using `TokenCredential` then 

a. the connection string must be validated to only contains a fully qualified namespace
b. or, the fully qualified namespace should be extracted from the connection string via `ServiceBusConnectionStringProperties.Parse(ConnectionString).FullyQualifiedNamespace`.

**Comment by LarsCelie** [comment]
My recommendation is using option b; automatically parse the connection string. This way, it will be much more intuitive.

**Comment by danielmarbach** [comment]
We have started implementing a solution for this, available in the following PR

https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/658/

The idea is to properly separate the connection string from the fully qualified namespace and the token credential. These are two different ways of connecting.
