### ISSUE TITLE
MessageLockLostException should not trigger critical errors

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Transport.AzureServiceBus#70]
## Who's affected

Anyone using transport.

## Symptoms

`MessageLockLostException` thrown by the transport is raising a [critical error](https://docs.particular.net/nservicebus/hosting/critical-errors), which in turn can cause endpoints to shutdown.

## Affected supported versions

- 1.2.x
- 1.1.x

## Original issue

**Describe the bug**
When a `MessageLockLostException` occurs during message processing, the error handling pipeline will be invoked. However, the error handling pipeline will also throw the same exception because it can't recover from this exception. When `onError` throws, this error is handled as a critical error.

Some hosts will shut down on critical errors (e.g. SC) which shouldn't happen on a MessageLockLostException.

**To Reproduce**
See this transport test reproducing the issue: https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/69

**Expected behavior**
Not sure whether `onError` should be called in the first place (e.g. moving message to the error queue) as I'd assume the message will be reprocessed anyway. So my first impression is that even the error handling pipeline shouldn't be invoked.

**Versions:**
latest master

**Comment by WojcikMike** [comment]
We have prioritized your issue and we will be working on it as of now to release the fix as soon as we can.

**Comment by odelljl** [comment]
This seems similar to the behavior that we have reported that occasionally stops out Service Control instance using the Azure Service Bus transport.  The service is in a stopped state after reporting this error.
