### ISSUE TITLE
Create queues when running installers

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Transport.AzureServiceBus#75]
It's been quite the different development workflow with the new transport so far, and the overhead so far is quite frustrating to me when juggling abstractions and names. 

I propose some sort of merge of old and new, either one or more of the below, in order of improved workflow, ideally point 3 of course 😉 

1. The scripts required for an endpoint could be generated (for example `endpoint.exe --exportOperationalScripts file.txt` where a file is created and each line contains a part of the script that can be picked up by deployments or a manual step.
1. The tool can be pointed to an endpoint and scans this for all required info and executes (essentially automating step 1 and the work to split up the file into separate commands).
1. The endpoint could opt in to automated provisioning by including some nuget package and specifically saying it wants to provision these resources on install. Something like:
    ```c#
    var transport = configuration.UseTransport<AzureServiceBusTransport>();
    transport.EnableProvisioningInstallers();
    ```
    This enable would only apply to people including this package and specifically opting in to the behavior.

**Comment by SeanFeldman** [comment]
Could you please what do you mean by the overhead? What is it with this transport that you find so challenging compared to the legacy one?
Thank you, @janpieterz.

**Comment by janpieterz** [comment]
@SeanFeldman Found out literally 30 seconds ago that subscriptions do seem to be added automatically?
Then it'd just be the endpoint creation, where before it created endpoint queues when running installers. But becomes quite a bit less of an issue.

As an aside, seems to be working very smooth besides that, trying a new part of the platform on it and then if all goes well migrating the other bits and pieces over, ASB standard seems decently stable this year so far.

**Comment by janpieterz** [comment]
Never mind, it seems to be exactly the same old lovely behavior. Probably was mucking around too much on the Saturday morning 😉

**Comment by SeanFeldman** [comment]
@janpieterz no worries. Glad to hear the weekend disaster was averted. 🙂
