### ISSUE TITLE
Default topic value not working in endpoint create

### ISSUE THREAD

**Issue by annebijlsma** [Particular/NServiceBus.Transport.AzureServiceBus#757]
**Describe the bug**
According to the [documentation](https://docs.particular.net/transports/azure-service-bus/operational-scripting#operational-scripting-asb-transport-endpoint-create), the default value of the topic name is 'bundle-1'. Until version 2.0.4, we were able to create both the queue and the subscription to the topic 'bundle-1' with the command "asb-transport.exe endpoint create $endpointName -c $connectionString". Since version 3.x, we noticed we start seeing errors when creating new endpoints. After investigation, I noticed the queue is still being created, but the subscription to the topic isn't. The error we receive is a 404 on the topic subscription when we execute the "asb-transport.exe endpoint subscribe" command to subscribe certain event(s) to the newly created subscription.

When diving into to the issue, I noticed there is an extra check added to the [Endpoint](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/master/src/CommandLine/Endpoint.cs#L22) class, which evaluates of the topicName parameter has a value. When I add the topic name to my original command, e.g. "asb-transport.exe endpoint create $endpointName -t "bundle-1" -c $connectionString", my subscription is now also created succesfully and after that also the subscription(s) are also added successfully to the subscription.

The default value 'bundle-1' is defined and used in the [Topic](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/master/src/CommandLine/Topic.cs) class, but the Topic.Create method is not called since the topicName HasValue() method evaluates to false if the topic name isn't defined in the command.

**Expected behavior**
I expect that the topic name 'bundle-1' can be used as the default and the -t/--topic option is not needed to create a new endpoint.

**Versions:**
 - NuGet package: 3.1.2
 - .NET Version 6

**Comment by danielmarbach** [comment]
@annebijlsma This is indeed a regression that we introduced when we added the possibility to have topology hierarchies that go beyond a single bundle topic. 

I have labeled this as a bug and sent in a fix https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/760
