### ISSUE TITLE
Migrating from ASB (legacy), How to migrate ForwardDeadLetteredMessagesTo

### ISSUE THREAD

**Issue by RiaanVR** [Particular/NServiceBus.Transport.AzureServiceBus#76]
I am currently trying to migrate to the new transport in a controlled manner, by creating a multi framework targetted NuGet package ontop of NServiceBus and the Transport libs, it would allow for a controlled upgrade across microservices. How can I migrate the calls to Queues() and Subscriptions(), such as ForwardDeadLetteredMessagesTo?

**Describe the solution you'd like**
Ideally, migrating to the new ASB transport would not be a breaking change, but if it must be I would like some documentation that indicates which methods are available and how to move away from certain calls.

**Comment by SeanFeldman** [comment]
Thank you for your feedback, @RiaanVR.
I'll just point out that the new transport [documentation](https://docs.particular.net/transports/azure-service-bus/) captures all the [configuration APIs](https://docs.particular.net/transports/azure-service-bus/configuration) that the new transport supports. It is backwards [compatible](https://docs.particular.net/transports/azure-service-bus/compatibility) with the legacy ASB on the forward topology. If you migrate from the legacy ASB on the endpoint-oriented topology, the migration is somewhat more sophisticated but possible. It's fully documented here: https://docs.particular.net/transports/azure-service-bus/legacy/migration.

>  migrating to the new ASB transport would not be a breaking change,

Please note that these are two completely different transport. The new ASB transport is not a continuation of the legacy ASB transport, it's a fundamentally different transport. As such, it has different behaviour when it comes to entity management, defaults, etc. The way the new transport was designed is to not interfere with the configurations customers are providing. That's an issue the legacy transport had. It was updating the entities whenever the endpoint would startup. To ensure user values are preserved, many of the `Queue` and `Subscription` configuration APIs were needed. The new transport will not modify entities if those exist. Therefore the need in `Queue` and `Subscription` is obsolete. Entities can be configured (dead-lettered forwarding, etc) and no transport code is needed to retain those user configurations.

>  but if it must be I would like some documentation that indicates which methods are available and how to move away from certain calls.

We took the minimalistic approach and decided not to "contaminate" the new transport with the information about the legacy transport. Similar to the reason the migration documentation is under the legacy of ASB transport and not the new one. We do have a section for [upgrade guides](https://docs.particular.net/transports/upgrades/), but not migration from one transport to another.   I wonder how would you imagine that documentation would look like? Contrasting the [legacy configuration API](https://docs.particular.net/transports/azure-service-bus/legacy/configuration/full) with the [new configuration API](https://docs.particular.net/transports/azure-service-bus/configuration) has very little in common.  Or how would it look like if you'd want to move from ASB transport to SQL Server transport?
