### ISSUE TITLE
Support AutoDeleteOnIdle

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Transport.AzureServiceBus#806]
### Describe the feature.

Related to https://github.com/Particular/NServiceBus/issues/6717, it might be worthwhile considering this feature specifically for the ASB transport rather than a basic transport seam feature.

**Comment by SeanFeldman** [comment]
Duplicate of https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/358?

**Comment by adamralph** [comment]
@timbussmann ?

**Comment by timbussmann** [comment]
yeah looks like a duplicate.
