### ISSUE TITLE
Support discarding of messages where the lock has expired while in the pre-fetch buffer. 

### ISSUE THREAD

**Issue by abroodie** [Particular/NServiceBus.Transport.AzureServiceBus#86]
We are currently experiencing issues with messages timing out while in the pre-fetch buffer when using using the Nservicebus.AzureServiceBus Transport (NServiceBus.Transport.AzureServiceBus). 
 This only seems to happen intermittently so I would prefer not to change the pre-fetch count as 99% of the time the messages in the pre-fetch buffer are processed with no issues.

**Describe the solution you'd like**
Allowing the consumer of the transport library to make the decision to discard/allow the message either by config on the transport (which would automagically discard the message and log a warning) or by exposing “LockedUntilUtc” via an incoming header.  (Is there a way to discard a message inside a mutator without throwing an exception?)

**Describe alternatives you've considered**
We’ve looked at using an incoming transport message mutator but it doesn’t contain enough info to handle determine if the message has timed out.

**Additional context**
Discussion of the issue with Sean Feldman:
https://discuss.particular.net/t/nservicebus-azureservicebustransport-message-lock-renewal/1504

**Comment by SeanFeldman** [comment]
Thank you @abroodie for feature suggestion.

A few questions to pick your brains on the topic.
1.  Today when the message loses its lock token, it's getting re-proccessed. What would you say the problem with the current state?
1. When a message is about to lose its lock token, but just not yet, what would you expect the desired behavior to be?
1. What time before lock is considered unusable?
1. Would that time be configurable?
1. Would you rather have the transport disregard the message or pass in a header with the `LockedUntilUtc` value?

**Comment by abroodie** [comment]
Hi Sean,  I think adding LockedUntilUtc as a new header would give us the most flexibility and also feels like less effort to implement.

**Comment by SeanFeldman** [comment]
Challenge with the header is that adding it at the transport level to the incoming message would mean it has to be preserved on the way out, which we don't want to do. Let me see what other options are possible.

**Comment by SeanFeldman** [comment]
Potentially a better option would be to pass the value under some agreed-upon key in the context bag that is available starting from the transport and available in the entire pipeline. Similar to the [code here](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/87/files#diff-8087c652ba124f20111530334b2bb2e1R58).

**Comment by abroodie** [comment]
that looks good too, would this be available on the context passed to a TransportMessageMutator too?

**Comment by SeanFeldman** [comment]
If you mean `IMutateIncomingTransportMessages`, no. Mutators would not help as they cannot influence the course of action in a way that would cause the message to be ignored rather than processed. Mutators can only mutate messages.

**Comment by SeanFeldman** [comment]
@abroodie the feature is available with version 1.4.0 and announced [here](https://discuss.particular.net/t/nservicebus-transport-azureservicebus-1-4-0-minor-release-available/1513).
